/* ==========================================================================
 *  Gesture Data Collection Firmware
 *  Target:  STM32F411RE (Nucleo-64)
 *  Sensor:  MPU-6050 (I2C1 — PB8 SCL, PB9 SDA)
 *  Output:  UART2 (Virtual COM Port) @ 115200 baud
 *  Trigger: Blue User Button (PC13, active LOW)
 *
 *  Format:  timestamp,accX,accY,accZ,gyroX,gyroY,gyroZ\r\n
 *           (raw 16-bit signed values, comma-separated)
 *
 *  Sampling rate: 50 Hz (20 ms period via HAL_Delay)
 *
 *  HOW TO USE:
 *  1. Create a new STM32CubeIDE project for STM32F411RETx.
 *  2. In the .ioc configurator, enable:
 *       - I2C1  (PB8 = SCL, PB9 = SDA)
 *       - USART2 (PA2 = TX, PA3 = RX) — already routed to ST-Link VCP
 *       - GPIO   PC13 as Input (no pull — external pull-up on Nucleo)
 *  3. Generate code, then replace the contents of Core/Src/main.c with
 *     this file.
 *  4. Build & flash.
 * ========================================================================== */

#include "main.h"
#include <stdio.h>
#include <string.h>

/* ---------- MPU-6050 Register Definitions -------------------------------- */
#define MPU6050_ADDR          (0x68 << 1)   /* 7-bit addr left-shifted for HAL */
#define MPU6050_REG_WHO_AM_I  0x75
#define MPU6050_REG_PWR_MGMT1 0x6B
#define MPU6050_REG_SMPLRT    0x19
#define MPU6050_REG_CONFIG    0x1A
#define MPU6050_REG_ACCEL_CFG 0x1C
#define MPU6050_REG_GYRO_CFG  0x1B
#define MPU6050_REG_ACCEL_XOUT_H 0x3B      /* start of 14-byte burst read */

/* ---------- Peripheral Handles (generated by CubeMX) --------------------- */
I2C_HandleTypeDef  hi2c1;
UART_HandleTypeDef huart2;

/* ---------- Private Function Prototypes ---------------------------------- */
static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);
static void MX_USART2_UART_Init(void);
static HAL_StatusTypeDef MPU6050_Init(void);
static HAL_StatusTypeDef MPU6050_ReadAll(int16_t *accel, int16_t *gyro);

/* ---------- printf redirect to UART2 ------------------------------------- */
int _write(int file, char *ptr, int len)
{
    HAL_UART_Transmit(&huart2, (uint8_t *)ptr, len, HAL_MAX_DELAY);
    return len;
}

/* ==========================================================================
 *  MAIN
 * ========================================================================== */
int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_USART2_UART_Init();

    /* ---- Initialise MPU-6050 ---- */
    if (MPU6050_Init() != HAL_OK)
    {
        /* Blink LED fast to signal init failure */
        while (1)
        {
            HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);   /* LD2 on Nucleo */
            HAL_Delay(100);
        }
    }

    /* Solid LED = sensor ready */
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_SET);

    uint32_t timestamp_ms = 0;
    int16_t  accel[3];   /* X, Y, Z */
    int16_t  gyro[3];    /* X, Y, Z */
    char     tx_buf[128];

    while (1)
    {
        /*  PC13 = Blue Button on Nucleo-64.
         *  It reads LOW when pressed (active-low with external pull-up).
         *  Data is transmitted ONLY while the button is held down.       */
        if (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13) == GPIO_PIN_RESET)
        {
            if (MPU6050_ReadAll(accel, gyro) == HAL_OK)
            {
                int len = snprintf(tx_buf, sizeof(tx_buf),
                    "%lu,%d,%d,%d,%d,%d,%d\r\n",
                    timestamp_ms,
                    accel[0], accel[1], accel[2],
                    gyro[0],  gyro[1],  gyro[2]);

                HAL_UART_Transmit(&huart2, (uint8_t *)tx_buf, len, HAL_MAX_DELAY);
            }

            /* Visual feedback: LED on while recording */
            HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_SET);
        }
        else
        {
            /* Reset timestamp when button is released so each gesture
             * recording starts from 0 ms — cleaner for Edge Impulse. */
            timestamp_ms = 0;

            /* Dim LED when idle */
            HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET);
        }

        HAL_Delay(20);          /* 50 Hz sampling */
        timestamp_ms += 20;
    }
}

/* ==========================================================================
 *  MPU-6050 Driver
 * ========================================================================== */

/**
 * @brief  Wake up the MPU-6050 and configure ranges / filter.
 *         Accel: ±2 g  |  Gyro: ±250 °/s  |  DLPF: ~44 Hz bandwidth
 */
static HAL_StatusTypeDef MPU6050_Init(void)
{
    uint8_t data;
    HAL_StatusTypeDef status;

    /* --- Verify WHO_AM_I (should return 0x68) --- */
    status = HAL_I2C_Mem_Read(&hi2c1, MPU6050_ADDR,
                              MPU6050_REG_WHO_AM_I, 1, &data, 1, 100);
    if (status != HAL_OK || data != 0x68)
        return HAL_ERROR;

    /* --- Wake up (clear SLEEP bit in PWR_MGMT_1, select PLL w/ X gyro) --- */
    data = 0x01;
    status = HAL_I2C_Mem_Write(&hi2c1, MPU6050_ADDR,
                               MPU6050_REG_PWR_MGMT1, 1, &data, 1, 100);
    if (status != HAL_OK) return status;
    HAL_Delay(50);   /* wait for PLL to stabilise */

    /* --- Sample rate divider: 1 kHz / (1+19) = 50 Hz --- */
    data = 19;
    status = HAL_I2C_Mem_Write(&hi2c1, MPU6050_ADDR,
                               MPU6050_REG_SMPLRT, 1, &data, 1, 100);
    if (status != HAL_OK) return status;

    /* --- DLPF config: BW ~44 Hz (index 3) --- */
    data = 0x03;
    status = HAL_I2C_Mem_Write(&hi2c1, MPU6050_ADDR,
                               MPU6050_REG_CONFIG, 1, &data, 1, 100);
    if (status != HAL_OK) return status;

    /* --- Accelerometer: ±2 g (AFS_SEL = 0) --- */
    data = 0x00;
    status = HAL_I2C_Mem_Write(&hi2c1, MPU6050_ADDR,
                               MPU6050_REG_ACCEL_CFG, 1, &data, 1, 100);
    if (status != HAL_OK) return status;

    /* --- Gyroscope: ±250 °/s (FS_SEL = 0) --- */
    data = 0x00;
    status = HAL_I2C_Mem_Write(&hi2c1, MPU6050_ADDR,
                               MPU6050_REG_GYRO_CFG, 1, &data, 1, 100);
    if (status != HAL_OK) return status;

    return HAL_OK;
}

/**
 * @brief  Burst-read all 6 axes (accel + gyro) in one I2C transaction.
 *         Registers 0x3B..0x48  (14 bytes: accXYZ, temp, gyroXYZ).
 *         Temperature is read but discarded.
 */
static HAL_StatusTypeDef MPU6050_ReadAll(int16_t *accel, int16_t *gyro)
{
    uint8_t raw[14];
    HAL_StatusTypeDef status;

    status = HAL_I2C_Mem_Read(&hi2c1, MPU6050_ADDR,
                              MPU6050_REG_ACCEL_XOUT_H, 1,
                              raw, 14, 100);
    if (status != HAL_OK)
        return status;

    /* Accel: bytes 0-5 (big-endian) */
    accel[0] = (int16_t)((raw[0]  << 8) | raw[1]);
    accel[1] = (int16_t)((raw[2]  << 8) | raw[3]);
    accel[2] = (int16_t)((raw[4]  << 8) | raw[5]);

    /* Skip bytes 6-7 (temperature) */

    /* Gyro: bytes 8-13 (big-endian) */
    gyro[0]  = (int16_t)((raw[8]  << 8) | raw[9]);
    gyro[1]  = (int16_t)((raw[10] << 8) | raw[11]);
    gyro[2]  = (int16_t)((raw[12] << 8) | raw[13]);

    return HAL_OK;
}

/* ==========================================================================
 *  CubeMX-style Peripheral Init Functions
 *  (Replace these with generated code if you use the .ioc configurator)
 * ========================================================================== */

static void SystemClock_Config(void)
{
    /* Configure HSI -> PLL -> 84 MHz SYSCLK (Nucleo default) */
    RCC_OscInitTypeDef       osc = {0};
    RCC_ClkInitTypeDef       clk = {0};

    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    osc.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    osc.HSIState       = RCC_HSI_ON;
    osc.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    osc.PLL.PLLState   = RCC_PLL_ON;
    osc.PLL.PLLSource  = RCC_PLLSOURCE_HSI;
    osc.PLL.PLLM       = 8;
    osc.PLL.PLLN       = 168;
    osc.PLL.PLLP       = RCC_PLLP_DIV4;     /* 84 MHz */
    osc.PLL.PLLQ       = 7;
    HAL_RCC_OscConfig(&osc);

    clk.ClockType      = RCC_CLOCKTYPE_HCLK  | RCC_CLOCKTYPE_SYSCLK |
                         RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    clk.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    clk.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    clk.APB1CLKDivider = RCC_HCLK_DIV2;      /* 42 MHz max for APB1 */
    clk.APB2CLKDivider = RCC_HCLK_DIV1;
    HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_2);
}

static void MX_I2C1_Init(void)
{
    __HAL_RCC_I2C1_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    /* PB8 = I2C1_SCL,  PB9 = I2C1_SDA */
    GPIO_InitTypeDef gpio = {0};
    gpio.Pin       = GPIO_PIN_8 | GPIO_PIN_9;
    gpio.Mode      = GPIO_MODE_AF_OD;
    gpio.Pull      = GPIO_PULLUP;
    gpio.Speed     = GPIO_SPEED_FREQ_VERY_HIGH;
    gpio.Alternate = GPIO_AF4_I2C1;
    HAL_GPIO_Init(GPIOB, &gpio);

    hi2c1.Instance             = I2C1;
    hi2c1.Init.ClockSpeed      = 400000;          /* 400 kHz Fast-mode */
    hi2c1.Init.DutyCycle       = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1     = 0;
    hi2c1.Init.AddressingMode  = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode   = I2C_NOSTRETCH_DISABLE;
    HAL_I2C_Init(&hi2c1);
}

static void MX_USART2_UART_Init(void)
{
    __HAL_RCC_USART2_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    /* PA2 = USART2_TX,  PA3 = USART2_RX */
    GPIO_InitTypeDef gpio = {0};
    gpio.Pin       = GPIO_PIN_2 | GPIO_PIN_3;
    gpio.Mode      = GPIO_MODE_AF_PP;
    gpio.Pull      = GPIO_NOPULL;
    gpio.Speed     = GPIO_SPEED_FREQ_VERY_HIGH;
    gpio.Alternate = GPIO_AF7_USART2;
    HAL_GPIO_Init(GPIOA, &gpio);

    huart2.Instance          = USART2;
    huart2.Init.BaudRate     = 115200;
    huart2.Init.WordLength   = UART_WORDLENGTH_8B;
    huart2.Init.StopBits     = UART_STOPBITS_1;
    huart2.Init.Parity       = UART_PARITY_NONE;
    huart2.Init.Mode         = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING16;
    HAL_UART_Init(&huart2);
}

static void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOC_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    /* PC13 — Blue User Button (input, no pull — external pull-up on board) */
    GPIO_InitTypeDef gpio = {0};
    gpio.Pin  = GPIO_PIN_13;
    gpio.Mode = GPIO_MODE_INPUT;
    gpio.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOC, &gpio);

    /* PA5 — LD2 green LED (output) */
    gpio.Pin   = GPIO_PIN_5;
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &gpio);
}
